title: "Langdoc-Minawao"
description: "Documentation and sociolinguistic research"
theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

markdown: kramdown

title: Langdocâ€“Minawao
show_title: false


